[phases.setup]
nixPkgs = ["gcc", "python311", "binutils", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python botrunner.py"
